# Generated by Django 5.2.8 on 2025-11-26 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_completion_time'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('captivate', 'Adobe Captivate'), ('scorm', 'SCORM Package'), ('html5', 'HTML5 Course'), ('articulate', 'Articulate Storyline')], default='captivate', max_length=20)),
                ('package_file', models.FileField(help_text='Original ZIP package', upload_to='interactive_courses/packages/%Y/%m/')),
                ('extracted_path', models.CharField(blank=True, help_text='Path to extracted content', max_length=500)),
                ('entry_file', models.CharField(default='index.html', help_text='Main HTML file to launch', max_length=255)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Estimated duration in minutes')),
                ('total_slides', models.IntegerField(default=0)),
                ('resolution_width', models.IntegerField(default=1280)),
                ('resolution_height', models.IntegerField(default=720)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='interactive_courses/thumbnails/')),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_courses', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactive_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactive_courses',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.IntegerField(default=0)),
                ('current_slide', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total time in seconds')),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('quiz_passed', models.BooleanField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scorm_data', models.JSONField(blank=True, default=dict)),
                ('interactive_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='videos.interactivecourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactive_course_progress',
                'unique_together': {('user', 'interactive_course')},
            },
        ),
    ]
