# Generated by Django 5.2.8 on 2025-12-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_interactivecourse_interactivecourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='content_completed',
            field=models.BooleanField(default=False, help_text='All slides viewed'),
        ),
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='content_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='highest_slide_reached',
            field=models.IntegerField(default=1, help_text='Highest slide number user has reached (no skipping)'),
        ),
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='slides_completed',
            field=models.JSONField(blank=True, default=dict, help_text='Track which slides are completed'),
        ),
        migrations.AlterField(
            model_name='interactivecourseprogress',
            name='current_slide',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interactivecourseprogress',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Course fully completed (content + quiz passed)'),
        ),
    ]
