# Generated by Django 5.2.8 on 2025-12-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_interactivecourseprogress_content_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivecourseprogress',
            name='current_slide',
            field=models.IntegerField(default=0, help_text='Current slide user is on (0 = not started)'),
        ),
        migrations.AlterField(
            model_name='interactivecourseprogress',
            name='highest_slide_reached',
            field=models.IntegerField(default=0, help_text='Highest slide number user has reached (no skipping)'),
        ),
        migrations.AlterField(
            model_name='interactivecourseprogress',
            name='total_time_spent',
            field=models.IntegerField(default=0, help_text='Total time in minutes'),
        ),
    ]
