# Generated by Django 5.2.8 on 2025-12-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_update_progress_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='scorm_suspend_data',
            field=models.TextField(blank=True, default='', help_text='SCORM suspend_data for course resume'),
        ),
    ]
