# Generated by Django 4.2.26 on 2025-11-07 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qr_code', models.ImageField(blank=True, upload_to='certificates/qr_codes/')),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/pdfs/')),
                ('verification_url', models.URLField(max_length=500)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issue_date'],
            },
        ),
    ]
