# Generated by Django 5.2.8 on 2025-12-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('videos', '0005_add_scorm_suspend_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='interactive_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='videos.interactivecourse'),
        ),
    ]
