# Generated by Django 4.2.26 on 2025-11-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head_of_risk', 'Head of Risk'), ('risk_compliance_specialist', 'Risk & Compliance Specialist'), ('banker', 'Banker')], default='banker', max_length=30),
        ),
    ]
