# Generated by Django 5.2.8 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('teller', 'Teller'), ('customer_service', 'Customer Service Officer'), ('branch_manager', 'Branch Manager'), ('loan_officer', 'Loan Officer'), ('operations_officer', 'Operations Officer'), ('it_officer', 'IT Officer'), ('accountant', 'Accountant'), ('auditor', 'Internal Auditor'), ('compliance_officer', 'Compliance Officer'), ('risk_analyst', 'Risk Analyst'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]

