# Generated by Django 4.2.27 on 2025-12-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
        ('accounts', '0004_alter_user_is_active'),
    ]

    operations = [
    ]
