# Generated by Django 5.2.8 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_departments',
            field=models.JSONField(blank=True, default=list, help_text='List of department keys that should be enrolled/targeted'),
        ),
    ]

