# Generated by Django 5.2.8 on 2025-12-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_completion_time'),
        ('quizzes', '0001_initial'),
        ('videos', '0005_add_scorm_suspend_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='interactive_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='videos.interactivecourse'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='interactive_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='videos.interactivecourse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.course'),
        ),
    ]
