# Generated by Django 5.2.8 on 2025-12-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='question_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of question IDs for this attempt'),
        ),
    ]
